### PR TITLE
Improve typing for decorators with `TypeVar`

### PR DESCRIPTION
**Pull request by mnixry**

### CODE REVIEW

**Comment by Krukov** [comment]
Thanks for this huge improvements of types annotations.

unfortunately tests failed, do you have time to fix it? or I can do it by myself

**Comment by Krukov** [comment]
@mnixry any updates ? Can I continue with this mr by myself?

**Comment by mnixry** [comment]
>  any updates ? Can I continue with this mr by myself?

Sorry for my reply latency. 

The reason of the test failing are caused by I've turned the backend class into an abstract class.
According to https://github.com/Krukov/cashews/issues/66#issuecomment-1139513031, it is great if we turn the backend class into an abstract class. It will have better typing and development experience (e.g, developers who want to develop the third-party backends will easily to know which method that they need to override).

To fix the failing test, there are two choices:
  - To brings backward compatibility, we can choose to revert the abstract class change
  - For better typing, we may need to create a new class (maybe `MockBackend`?) for this, and it may bring some breaking change for third-party developer.

So I think it will be better to decide by you.

**Comment by mnixry** [comment]
By the way, if we have the typing support good enough, we can add https://github.com/mypyc/mypyc to create compiled binary for package, which can improve the package performance 2x-4x according to some benchmark.

**Comment by Krukov** [comment]
Thanks, I will try to keep Backend as Abstract class, I will notes you for review my changes if you don't mind

**Pull request merged**
